/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/confirm-pair` | `/confirm-pair`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/find-runtime` | `/find-runtime`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/pair-success` | `/pair-success`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/session/[sessionId]` | `/session/[sessionId]`, params: Router.UnknownInputParams & { sessionId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/confirm-pair` | `/confirm-pair`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/find-runtime` | `/find-runtime`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/pair-success` | `/pair-success`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/welcome` | `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/session/[sessionId]` | `/session/[sessionId]`, params: Router.UnknownOutputParams & { sessionId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(main)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/confirm-pair${`?${string}` | `#${string}` | ''}` | `/confirm-pair${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/find-runtime${`?${string}` | `#${string}` | ''}` | `/find-runtime${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/pair-success${`?${string}` | `#${string}` | ''}` | `/pair-success${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/welcome${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/confirm-pair` | `/confirm-pair`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/find-runtime` | `/find-runtime`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/pair-success` | `/pair-success`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | `${'/(main)'}/session/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/session/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(main)'}/session/[sessionId]` | `/session/[sessionId]`, params: Router.UnknownInputParams & { sessionId: string | number; } };
    }
  }
}
